sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

cache: yarn

language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'

after_script: 'npm install coveralls@2 && cat ./coverage/lcov.info | coveralls'
