#%RAML 1.0 DataType
pattern: "^(?:(?:(\\d{1,3}|\\d{0,3}\\.\\d+)%\\s*)?([a-z]+)|#([0-9a-f]{3}(?:[0-9a-f](?:[0-9a-f]{2}){0,2})?))$"
examples:
  named: "red"
  namedAlpha: "50% red"
  rgb: "#f00"
  rgba: "#f008"
  rrggbb: "#ff0000"
  rrggbbaa: "#ff000080"
