#%RAML 1.0
title: ckb-cloud
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: localhost:3007/{version}
mediaType: application/json

types:
  Client:         !include types/client.raml
  Key:            !include types/key.raml
  Color:          !include types/color.raml
  ColorStop:      !include types/colorStop.raml
  Effect:         !include types/effect.raml
  ColorEffect:    !include types/colorEffect.raml
  GradientEffect: !include types/gradientEffect.raml

resourceTypes:
  collection:     !include resourceTypes/collection.raml
  member:         !include resourceTypes/member.raml

/clients:
  type: { collection: { resourceType: Client } }
  /{client_id}:
    type: { member: { resourceType: Client } }
    /keys:
      type: { collection: { resourceType: Key } }
      /{key_id}:
        type: { member: { resourceType: Key } }
        /effects:
          type: { collection: { resourceType: Effect } }
          post:
          delete:
          /{effect_id}:
            type: { member: { resourceType: Effect } }
            delete:
