#%RAML 1.0
title: ckb-cloud
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: localhost:3007/{version}
mediaType: application/json

uses:
  Effects:    libraries/types/effects.raml
  Collection: libraries/resourceTypes/collection.raml

types:
  Client:     !include types/client.raml
  Key:        !include types/key.raml
  ApiRoot:    !include types/api-root.raml

/:
  get:
    responses:
      200:
        body: ApiRoot
/clients:
  type: { Collection.member: {resourceType: Client } }
  /{client_id}:
    type: { Collection.member: { resourceType: Client } }
    /keys:
      type: { Collection.collection: { resourceType: Key } }
      /{key_id}:
        type: { Collection.member: { resourceType: Key } }
        /effects:
          type: { Collection.collection: { resourceType : Effects.Effect } }
          post:
          delete:
          /{effect_id}:
            type: { Collection.member: { resourceType: Effects.Effect } }
            delete:
